apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "weather.fullname" . }}-redis
  labels:
    {{- include "weather.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "weather.selectorLabels" . | nindent 6 }}-redis
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "weather.labels" . | replace .Release.Name (printf "%s-redis" .Release.Name) | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "weather.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-redis
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository_redis }}:{{ .Values.image.tag_redis | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: {{ .Values.env.redis_user }}
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.env.configmap_name }} 
                  key: {{ .Values.env.redis_user }}
            - name: {{ .Values.env.redis_password }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secret_name }}
                  key: {{ .Values.env.redis_password }}
          ports:
            - containerPort: {{ .Values.service.port_redis }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          hostPath:
            path: /data/redis-data

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "weather.fullname" . }}-redis
  labels:
    {{- include "weather.labels" . | nindent 4 }}
spec:
  selector:
    app:     {{- include "weather.selectorLabels" . | nindent 4 }}-redis
  ports:
    - protocol: TCP
      port: {{ .Values.service.port_redis }}
      targetPort: {{ .Values.service.port_redis }}
  type: {{ .Values.service.type }}
