apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "weather.fullname" . }}-ui
  labels:
    {{- include "weather.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "weather.selectorLabels" . | nindent 6 }}-ui
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "weather.labels" . | replace .Release.Name (printf "%s-ui" .Release.Name) | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "weather.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-ui
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository_ui }}:{{ .Values.image.tag_ui | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port_ui }}
              protocol: TCP
          env:
            - name: {{ .Values.env.auth_host }}
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.env.configmap_name }} 
                  key: {{ .Values.env.auth_host }}
            - name: {{ .Values.env.auth_port }}
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.env.configmap_name }} 
                  key: {{ .Values.env.auth_port }}
            - name: {{ .Values.env.weather_host }}
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.env.configmap_name }} 
                  key: {{ .Values.env.weather_host }}
            - name: {{ .Values.env.weather_port }}
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.env.configmap_name }} 
                  key: {{ .Values.env.weather_port }}
            - name: {{ .Values.env.redis_user }}
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.env.configmap_name }} 
                  key: {{ .Values.env.redis_user }}
            - name: {{ .Values.env.redis_password }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secret_name }} 
                  key: {{ .Values.env.redis_password }}
            - name: {{ .Values.env.redis_host }}
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.env.configmap_name }} 
                  key: {{ .Values.env.redis_host }}


          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "weather.fullname" . }}-ui
  labels:
    {{- include "weather.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type_ui }}
  ports:
    - port: {{ .Values.service.port_ui }}
      targetPort: {{ .Values.service.target_port_ui }}
      protocol: TCP
      name: http
  selector:
    {{- include "weather.selectorLabels" . | nindent 4 }}-ui
